[package]
name = "Calc"
version = "1.2.0"
authors = ["lhjok <lhjok@live.cn>"]
edition = "2018"

[dependencies]
ansi_term = "0.11"

[dependencies.rug]
version = "1.6"
default-features = false
features = ["float"]
